### ISSUE TITLE
Heredoc indentation

### ISSUE THREAD

**Issue by voltechs** [tmichel/sublime-terraform#7]
Terraform allows for [indenting heredocs](https://www.terraform.io/language/expressions/strings#indented-heredocs), which improves readability. The plugin currently does not detect this for highlighting properly.

![Screen Shot 2022-01-06 at 12 21 01](https://user-images.githubusercontent.com/1700514/148439080-c979e8b4-25bc-4673-a6a1-a8f2c55281ee.png)
![Screen Shot 2022-01-06 at 12 21 20](https://user-images.githubusercontent.com/1700514/148439111-c3afdfb1-ba8f-454e-a341-cbc24d6055e3.png)
![Screen Shot 2022-01-06 at 12 21 29](https://user-images.githubusercontent.com/1700514/148439124-7e9df7ef-f6ca-4d29-b06b-073a521c7bd5.png)

**Comment by voltechs** [comment]
For posterity, [this plugin](https://github.com/alexlouden/Terraform.tmLanguage) does support it (for those looking for an alternative).

**Comment by tmichel** [comment]
I added support for indented heredocs. If you update the plugin they will hopefully start getting recognized.
